---

- name: packages update list
  apt: >
    update_cache=yes
    cache_valid_time=180
  sudo: yes

- name: packages
  apt: >
    name={{ item }}
    state=latest
  with_items:
    - python-dev
    - python-pip
    - libcairo2-dev
    - memcached
  sudo: yes