---

- name: Installing Python packages
  pip:  name={{ item.name }} {% if item.version is defined %}version={{ item.version }}{% endif %}
  sudo: yes
  with_items:
    - { name: django,  version: 1.5 }
    - { name: twisted, version: 11.0.0 }
    - { name: python-memcached, version: 1.47 }
    - { name: txAMQP, version: 0.4 }
    - { name: django-tagging, version: 0.3.2 }
    - { name: gunicorn, version: 19.1.1 }
    - { name: "git+git://github.com/graphite-project/whisper.git#egg=whisper", version: 0.9.12 }
    - { name: "PyYAML", version: 3.11 }

- name: Getting cairo
  get_url: url="http://cairographics.org/releases/py2cairo-1.8.10.tar.gz" dest="/tmp"
 args:
    creates: /tmp/py2cairo-1.8.10.tar.gz

- name: Uncompressing cairo
  shell: > 
    tar xfz /tmp/py2cairo-1.8.10.tar.gz
  args:
    creates: /tmp/py2cairo-1.8.10

- name: Installing cairo
  shell: >
    ./configure && make && make install
  args:
    chdir: /tmp/pycairo-1.8.10
    creates: /usr/local/include/pycairo